name: clj-kondo checks

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2024.05.24'

    - name: Lint
      run: clj-kondo --parallel --lint src test --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
